/**
 * Licences
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 03da231e-857d-47ad-b88b-19a9edef6ede
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelObject } from './modelObject';

export interface Model201User { 
    role?: string;
    id?: string;
    firstName?: string;
    lastName?: string;
    phone?: string;
    email?: string;
    createdAt?: string;
    updatedAt?: string;
    v?: ModelObject;
}